describe('Dashboard', () => {
  beforeEach(() => {
    cy.intercept('GET', 'https://botw-compendium.herokuapp.com/api/v2/category/materials', {fixture: 'items.json'})
    cy.visit('http://localhost:3000/')
  });
  it('should have access to the Zeldas Compendium website', () => {
  })
  it('should display the websites logo and name on page load', () => {
    cy.get('.website-logo')
      .should('be.visible')
    cy.get('.website-name')
      .should('be.visible')
  })
  it('should display a search bar and its label on page load', () => {
    cy.get('.search-label')
      .should('be.visible')
    cy.get('.search-input')
      .should('be.visible')
      .should('be.empty')
    cy.get('.submit-input')
      .should('be.visible')
  })
  it('should display item cards for individual items on page load', () => {
    cy.get('.item-card')
      .should('be.visible')
      .find('.item-image')
      .should('be.visible')
    cy.get('.item-card')
      .find('.card-name')
      .should('be.visible')
  })
  it('should redirect you to a items detail page when an item card is clicked', () => {
    cy.get('[id=182]')
      .click()
    cy.get('.ItemDetails')
      .find('.item-name')
      .should('contain', 'Rushroom')
      .should('be.visible')
  })
  it('should redirect you to an items detail page when an item is searched in the search bar', () => {
    cy.get('.search-input')
      .type('rushroom')
    cy.get('.submit-input')
      .click()
    cy.get('.ItemDetails')
      .find('.item-name')
      .should('contain', 'Rushroom')
      .should('be.visible')
  })
  it('should redict you to an error page that displayes a 404 error when no item matches the search input', () => {
    cy.get('.search-input')
      .type('rushplant')
    cy.get('.submit-input')
      .click()
    cy.get('.ErrorPage')
      .find('.error-text')
      .contains('Something went wrong: 404 Page not found')
  })
  it('should redict you to an error page when a bad URL is typed in', () => {
    cy.visit('http://localhost:3000/nope')
    cy.get('.ErrorPage')
      .find('.error-text')
      .contains('Something went wrong')
  })
  it('should contain a button that redirects you to the main page when a bad URL is typed', () => {
    cy.visit('http://localhost:3000/nope')
    cy.get('.ErrorPage')
      .find('.error-return-button')
      .click()
    cy.get('form')
      .should('be.visible')
    cy.get('.card-container')
      .should('be.visible')
  })
  it('should contain a button that redirects you to the main page when a search item doesnt exist', () => {
    cy.get('.search-input')
      .type('rushplant')
    cy.get('.submit-input')
      .click()
    cy.get('.ErrorPage')
      .find('.error-return-button')
      .click()
    cy.get('form')
      .should('be.visible')
    cy.get('.card-container')
      .should('be.visible')
  })
})